// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvaoshuemkcolfattuqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2YW9zaHVlbWtjb2xmYXR0dXF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxOTE4ODUsImV4cCI6MjA3Mjc2Nzg4NX0.Taf3Hjgeo58x2bAaA8yKJJW72uZh2XcK0NYaF9RK9R4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});